# -*- coding: utf-8 -*-
"""Outliers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bMKDwcsgwgRjUn7PHawv5QlPO6TZIxmT
"""

print("Hello world")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(uploaded['placement.csv']))

df

plt.figure(figsize=(16,5))
plt.subplot(1,2,1)
sns.distplot(df['cgpa'])

plt.subplot(1,2,2)
sns.distplot(df['placement_exam_marks'])

df.info()

# box plot
sns.boxplot(df['cgpa'])

df['cgpa'].mean()

df['cgpa'].std()

df['cgpa'].min()

df['cgpa'].max()

df.shape

"""Detecting The Outliers"""

# Detecting the outliers

df[(df['cgpa']>8.5) | (df['cgpa']<5)]

df[df['cgpa']<4.8]

"""Trimming"""

newdf = df[(df['cgpa']<8.5) & (df['cgpa']>5)]

newdf.shape

newdf

sns.boxplot(newdf['cgpa'])

"""# Capping"""

# ub = mean+3*std
# lb = mean-3*std
upper_limit = df['cgpa'].mean() + 3*df['cgpa'].std()

upper_limit

lower_limit = df['cgpa'].mean() - 3*df['cgpa'].std()

lower_limit

df1 = np.where(df['cgpa']>upper_limit,upper_limit,
               np.where(df['cgpa']<lower_limit,lower_limit,
                        df['cgpa']))

df1.shape

sns.boxplot(df1)

